workdir = "aipy_work"
record = true
max_tokens = 4096
default_llm_provider = "openrouter"

[llm.openrouter]
type = "openai"
model = "deepseek/deepseek-chat-v3-0324:free"
api_key = ""
base_url = "https://openrouter.ai/api/v1"
enable = true
default = true
timeout = 30
max_tokens = 8192

[llm.grok]
type = "openai"
model = "grok-3-mini"
api_key = ""
base_url = "https://api.x.ai/v1/"
enable = true
default = false
timeout = 30
max_tokens = 8192

[llm.qwen]
type = "openai"
model = "openai/qwen-max"
api_key = ""
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
enable = true
default = false
timeout = 30
max_tokens = 8192

[llm.gemini]
type = "openai"
model = "gemini-2.5-pro-exp-03-25"
api_key = ""
base_url = "https://generativelanguage.googleapis.com/v1beta/"
enable = true
default = false
timeout = 30
max_tokens = 8192

[llm.ollama]
type = "ollama"
model = "llama3"
api_key = ""
base_url = "http://localhost:11434"
enable = true
default = false
timeout = 30
max_tokens = 8192

[llm.deepseek]
type = "openai"
model = "openai/deepseek-chat-v3-0324"
api_key = ""
base_url = "https://api.deepseek.com"
enable = true
default = false
timeout = 30
max_tokens = 8192
